### ISSUE TITLE
Delete this repo. You stole my copyrighted content.

### ISSUE THREAD

**Issue by jakedeichert** [killerrin/killerrin.github.io#1]
Andrew, I am extremely shocked you have illegally ripped my website.

As you saw in my footer, I have personal copyright on the source code for my website. Stealing copyrighted content is not okay.

I am asking you to remove the source code in this repository and to delete any copies you have.

I don't understand why you would copy someone else's code. There's millions of free website templates, yet you made a poor decision of taking a copyrighted one.

I'll give you 3 days to respond before I take further action with GitHub and the DMCA process.

Feel free to explain to me why you would do this.

**Comment by killerrin** [comment]
Alright, I'll take it down and delete the stuff.

Only reason was because I really liked how the template looked, over time I was going to change it to something else, though I guess looking at it now it wasn't the best of decisions
